name: ball_sort_game
description: Ball sorting puzzle with 15 tubes × 12 balls.
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  audioplayers: ^5.2.1
  # Monetization
  in_app_purchase: ^3.1.11
  google_mobile_ads: ^6.0.0
  # Analytics
  firebase_analytics: ^10.7.4
  firebase_crashlytics: ^3.4.9
  # Platform Services
  # game_services: ^0.0.2
  # Web Optimization
  url_launcher: ^6.2.2
  share_plus: ^7.2.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/balls/
    - assets/sounds/

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: assets/app_icon.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/app_icon.png
