name: ball_sort_game
description: Ball sorting puzzle with 15 tubes × 12 balls.
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3

flutter:
  uses-material-design: true
  assets:
    - assets/balls/
